<a href="https://colab.research.google.com/github/adiknur007/ML/blob/main/%D0%A2%D0%A25_%D0%B0%D0%BF%D1%82%D0%B0_%D0%9D%D2%B1%D1%80%D1%82%D0%B0%D0%B5%D0%B2%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Есеп 1.1:

---
Екі 3×3 матрица құрып, олардың қосындысын, айырмасын және көбейтіндісін табыңыз.

In [1]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])

print("A + B:\n", A + B)
print("A - B:\n", A - B)
print("A * B:\n", A.dot(B))



A + B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
A - B:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
A * B:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


# Есеп 2.1:

---

3 өлшемді екі вектордың скаляр көбейтіндісін және олардың арасындағы бұрышты есептеңіз.

In [2]:
import numpy as np
import math

# Векторларды енгізу
a = np.array([1, 2, 3])
b = np.array([4, -5, 6])

# 1. Скаляр көбейтінді
dot_product = np.dot(a, b)

# 2. Векторлардың ұзындықтары
a_len = np.linalg.norm(a)
b_len = np.linalg.norm(b)

# 3. Араларындағы бұрыш
cos_theta = dot_product / (a_len * b_len)
theta_radians = math.acos(cos_theta)       # радиан
theta_degrees = math.degrees(theta_radians)  # градус

print("Скаляр көбейтінді:", dot_product)
print("a векторының ұзындығы:", a_len)
print("b векторының ұзындығы:", b_len)
print("Бұрыш (радиан):", theta_radians)
print("Бұрыш (градус):", theta_degrees)


Скаляр көбейтінді: 12
a векторының ұзындығы: 3.7416573867739413
b векторының ұзындығы: 8.774964387392123
Бұрыш (радиан): 1.1966404427876283
Бұрыш (градус): 68.56244696639715


# Есеп 3.1:


---

Берілген матрицаның детерминантын, кері матрицасын және өз мәндерін табыңыз.

In [3]:
import numpy as np
import math

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]], dtype=float)

det = np.linalg.det(A)
print("det(A) =", det)

if abs(det) < 1e-12:
    print("A матрицасы сингуляр — кері матрица жоқ.")
else:
    A_inv = np.linalg.inv(A)
    print("A^-1 =\n", A_inv)

eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues:", eigvals)
print("Eigenvectors (columns):\n", eigvecs)


det(A) = 0.0
A матрицасы сингуляр — кері матрица жоқ.
Eigenvalues: [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Eigenvectors (columns):
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


# Есеп 4.1:
np.random.randn() арқылы 1000 элементтік үлгі алыңыз және орташа, дисперсия мен стандартты ауытқуды есептеңіз.

In [4]:
import numpy as np

# 1000 элементтік үлгі
ran = np.random.randn(1000)

# Орташа мән
mean = ran.mean()

# Дисперсия
variance = ran.var()

# Стандартты ауытқу
std_dev = ran.std()

print("Орташа мән:", mean)
print("Дисперсия:", variance)
print("Стандартты ауытқу:", std_dev)


Орташа мән: -0.03507770923515747
Дисперсия: 0.9550346982711763
Стандартты ауытқу: 0.9772587673033055


# Есеп 5.1:
Берілген тізім: [5, 10, 15, 20, 25] — үшін Min-Max және Z-score нормализациясын орындаңыз.

In [5]:
import numpy as np

data = np.array([5, 10, 15, 20, 25])

# Min-Max Normalization
min_max = (data - data.min()) / (data.max() - data.min())

# Z-score Normalization
mean = data.mean()
std = data.std()
zscore = (data - mean) / std

print("Min-Max:", min_max)
print("Z-score:", zscore)


Min-Max: [0.   0.25 0.5  0.75 1.  ]
Z-score: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
